### ISSUE TITLE
Parsing numbers starting with 0 is not supported

### ISSUE THREAD

**Issue by Shnatsel** [RoDmitry/atoi_simd#3]
Add the following test to the codebase:

```rust
#[test]
fn test_parse_i64_fuzzed() {
    let input = b"02221222122210221223";
    let result = parse::<i64>(input).unwrap();
    assert_eq!(result, 02221222122210221223);
}
```

Run it with SIMD disabled (with the `.cargo/config.toml` file deleted) and you'll see that it fails. Meanwhile the standard library parses this number correctly.

This bug was discovered using `cargo-fuzz`. You can find a guide to it [here](https://rust-fuzz.github.io/book/cargo-fuzz.html) and the fuzzing setup I used [here](https://github.com/Shnatsel/atoi_simd/blob/fd9d5ab32473a31915509bbc3d9c5aed605c5170/fuzz/fuzz_targets/parse_i64.rs). I will contribute the fuzzing setup to your repository eventually.

**Comment by Shnatsel** [comment]
Actually, it fails with SIMD enabled as well. So turning SIMD on/off doesn't make any difference.

**Comment by Shnatsel** [comment]
I am also getting a similar error when trying to parse `0000000000000000000000000000000000000001`

The standard library implementation also handles this one correctly.

**Comment by RoDmitry** [comment]
Zeroes at the beginning of the input are not supported by the design, and I am not sure if it's needed, because it will work slower.

**Comment by Shnatsel** [comment]
I see, thanks for clarification.

Parsing numbers with leading zeroes is something people also need to do, and I think this library could do it faster than `str::strip_leading_maches('0')`. There are ways to quickly count leading decimal zeroes with SIMD: https://github.com/KholdStare/qnd-integer-parsing-experiments/issues/2

**Comment by RoDmitry** [comment]
Hm, it might be not that slow. Will think about it, thanks

**Comment by RoDmitry** [comment]
Test 228836832f162352cf17699f1feebaa557e11573

**Comment by Shnatsel** [comment]
FWIW the standard library parser supports even longer sequences of leading zeroes, so that 000000000000000001 does parse correctly into a `u16`.

It's up to you whether you choose to support this use case.

**Comment by RoDmitry** [comment]
I just don't see any use cases. If anybody needs it, write it here, with explanation of the use case, would be interesting to know.

**Comment by RoDmitry** [comment]
Done in a separate function atoi_simd::parse_full
