### ISSUE TITLE
Parsing numbers starting with `+` is not supported

### ISSUE THREAD

**Issue by Shnatsel** [RoDmitry/atoi_simd#4]
This could be considered an edge case, but the standard library's parsing routines do support it, so reporting it for your consideration. Example on which the divergence can be observed: `+0`

**Comment by RoDmitry** [comment]
There is a check for `-`. Probably it's an easy fix, but I did not need that previously

**Comment by Shnatsel** [comment]
I think this and zeroes are the only two things that std supports and your crate doesn't. So if you can support them, that would make `atoi_simd` a drop-in replacement for std functions :raised_hands: 

I'd like to see a release without UB first though. It's easy to get sidetracked :sweat_smile:

**Comment by RoDmitry** [comment]
Done in separate function `atoi_simd::parse_full`
