### ISSUE TITLE
Parsing very large `i32` and `u32` returns an incorrect number instead of an error

### ISSUE THREAD

**Issue by Shnatsel** [RoDmitry/atoi_simd#5]
The following test case causes an integer overflow:

```rust
#[test]
fn overflow() {
    let input = [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 56, 55, 55, 55, 55, 55, 55, 55, 55, 56, 45];
    crate::parse::<i32>(&input);
}
```

It happens in this line:

https://github.com/RoDmitry/atoi_simd/blob/ba43ae89a061a663725ef93450f2da0cb40e2750/src/short.rs#L37

Integer overflow panics in debug mode by default. If you are confident this overflow is benign, `wrapping_add` and `wrapping_mul` should be used. If it needs to be handled for correctness, use [`checked_mul`](https://doc.rust-lang.org/stable/std/primitive.i32.html#method.checked_mul) (which looks like it would be more efficient than the `overflow!` macro, but I'm not willing to claim that without benchmarks).

**Comment by Shnatsel** [comment]
Ditto for u32:

```rust
#[test]
fn overflow_u32() {
    let input = [48, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 48, 208, 48, 1];
    crate::parse::<u32>(&input);
}
```

**Comment by Shnatsel** [comment]
It seems that this overflow is a genuine issue because when parsing `-2002262000620062000000` (in `&[u8]` notation `[45, 50, 48, 48, 50, 50, 54, 50, 48, 48, 48, 54, 50, 48, 48, 54, 50, 48, 48, 48, 48, 48, 48]`) to i32, `atoi_simd` incorrectly returns `-230835072` while the standard library correctly reports that the number doesn't fit.

**Comment by Shnatsel** [comment]
Same issue in `u32` when trying to parse `3000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

**Comment by Shnatsel** [comment]
Same issue for fallback impls of `u8`, `u16`, `i8`, `i16`.

**Comment by RoDmitry** [comment]
Fixed

**Comment by Shnatsel** [comment]
Can confirm
