### ISSUE TITLE
Some `u128` and `i128` values are parsed incorrectly instead of returning an error

### ISSUE THREAD

**Issue by Shnatsel** [RoDmitry/atoi_simd#7]
The number "707071770707000177170017011770740070701" (or, in `&[u8]` notation, `[55, 48, 55, 48, 55, 49, 55, 55, 48, 55, 48, 55, 48, 48, 48, 49, 55, 55, 49, 55, 48, 48, 49, 55, 48, 49, 49, 55, 55, 48, 55, 52, 48, 48, 55, 48, 55, 48, 49]`) is parsed as `26507036865123250243267796907203647789` by `atoi_simd`. The standard library correctly returns an error in this case.

It only happens with AVX enabled, so it is likely a symptom of #6

Found using `cargo fuzz`

**Comment by RoDmitry** [comment]
On my pc it overflows as #6

**Comment by RoDmitry** [comment]
I think it is fixed with #6. Check again

**Comment by Shnatsel** [comment]
Indeed. Thanks for the quick fix!
